-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: v0.8.0
    hooks:
    -   id: flake8
        exclude: service/protos|client|protos
        args:
        - --max-line-length=120
    -   id: check-docstring-first
    -   id: debug-statements
-   repo: https://github.com/asottile/reorder_python_imports
    sha: v0.3.5
    hooks:
    -   id: reorder-python-imports
        language_version: python3.6
        args:
        - --separate-relative
        - --separate-from-import
        - --remove-import
        - from __future__ import absolute_import
        - --remove-import
        - from __future__ import division
        - --remove-import
        - from __future__ import print_function
        - --remove-import
        - from __future__ import unicode_literals
        - --remove-import
        - from __future__ import with_statement
-   repo: https://github.com/asottile/pyupgrade
    sha: v1.1.1
    hooks:
    -   id: pyupgrade
-   repo: https://github.com/Botpy/pre-commit-pylint.git
    sha: v0.0.2
    hooks:
    -   id: pylint-score-limit
        exclude: service/protos|client|protos
        args:
        - --limit=8.5
        - --rcfile=./.pylintrc

